name: Auto Deployment

on:
  push:
    branches: [deploy]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH KEY
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Add host key to known hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          HOST_NAME: ${{ secrets.VPS_HOST }}
          USER_NAME: ${{ secrets.VPS_USERNAME }}
        run: |
          ssh $USER_NAME@$HOST_NAME '
            cd ${{ secrets.DEPLOY_PATH }}
            source ~/.zshrc
            git switch main 
            git pull
            bun install
            bun run build
            pm2 reload ecosystem.config.cjs
          '
